#!/usr/bin/env python3
"""Writes thunder/thunder-items-data.js: which newer item a server really sent.

    python3 thunder/packs/item_ids.py [--cache DIR]

A newer server (through ViaBackwards) sends a 1.12 client every item 1.12 does not have as an old
item. Besides the name ("1.21.11 Netherite Spear") it keeps the item's real id in the item's data,
under "VB|Protocol<newer>To<older>|id": the item's number in the newer version's item list. The
name is not there when the server already gave the item a name of its own, the id is.

For every ViaBackwards step that adds items (1.14 and up) this script lists the numbers of the items
that are new in that step, and for every item added since 1.12 the model name that
build_packs.py gives it (item/thunder/<English name in lower_case_words>). The item lists come
from PrismarineJS minecraft-data, the English names from the 1.21.11 language file. Downloads are
cached in ~/.cache/thunder-packs/ids; the output is the same every run.
"""
import argparse
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'thunder', 'thunder-items-data.js')
MCDATA = 'https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/'
LANG = ('https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.21.11/'
        'assets/minecraft/lang/en_us.json')

# ViaBackwards protocol steps (newer <- older) from 1.14 on. The class name is what goes into the tag.
STEPS = [('1.14', '1.13.2'), ('1.15', '1.14.4'), ('1.16', '1.15.2'), ('1.16.2', '1.16.1'),
         ('1.17', '1.16.4'), ('1.18', '1.17.1'), ('1.19', '1.18.2'), ('1.19.3', '1.19.1'),
         ('1.19.4', '1.19.3'), ('1.20', '1.19.4'), ('1.20.2', '1.20'), ('1.20.3', '1.20.2'),
         ('1.20.5', '1.20.3'), ('1.21', '1.20.5'), ('1.21.2', '1.21'), ('1.21.4', '1.21.2'),
         ('1.21.5', '1.21.4'), ('1.21.6', '1.21.5'), ('1.21.7', '1.21.6'), ('1.21.9', '1.21.7'),
         ('1.21.11', '1.21.9')]
# versions minecraft-data does not list, and the release with the same item list that it does
SAME = {'1.19.1': '1.19.2', '1.21.2': '1.21.3', '1.21.7': '1.21.8'}



def fetch(url, cache, name):
    f = os.path.join(cache, name)
    if not os.path.exists(f):
        os.makedirs(cache, exist_ok=True)
        with urllib.request.urlopen(url, timeout=60) as r:
            data = r.read()
        with open(f, 'wb') as o:
            o.write(data)
    with open(f, 'rb') as i:
        return json.loads(i.read())


def items(v, cache):
    """{id: name} of one version's item list (minecraft-data's dataPaths.json says which folder has it)."""
    d = fetch(MCDATA + 'dataPaths.json', cache, 'dataPaths.json')['pc'][SAME.get(v, v)]['items']
    return {it['id']: it['name'] for it in fetch(MCDATA + d + '/items.json', cache, 'items-%s.json' % d.split('/')[-1])}


def model_key(name):
    """'Netherite Spear' -> 'netherite_spear' (the same rule as build_packs.py and thunder-items.js)."""
    return re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')


def cls(v):
    return v.replace('.', '_')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache', default=os.path.join(os.path.expanduser('~'), '.cache', 'thunder-packs', 'ids'))
    args = ap.parse_args()
    lang = fetch(LANG, args.cache, 'en_us-1.21.11.json')
    ids, keys = {}, {}
    for new, prev in STEPS:
        a, b = items(new, args.cache), set(items(prev, args.cache).values())
        added = {i: n for i, n in a.items() if n not in b}
        if added:
            ids['VB|Protocol%sTo%s|id' % (cls(new), cls(prev))] = {str(i): n for i, n in sorted(added.items())}
        for n in added.values():
            name = lang.get('item.minecraft.' + n)
            if name:
                keys[n] = model_key(name)
    # only items the pack can have a model for (blocks and the like are left out)
    ids = {t: {i: n for i, n in v.items() if n in keys} for t, v in ids.items()}
    ids = {t: v for t, v in ids.items() if v}
    total = sum(len(v) for v in ids.values())
    with open(OUT, 'w', encoding='ascii') as o:
        o.write('  /* Generated by thunder/packs/item_ids.py - do not edit. Part of Thunder Client, created and\n'
                '     owned by Jayvardhan Ginni (ThunderGamey). NI_TAGS: ViaBackwards item tag (newest step first)\n'
                '     -> {number in that version: newer item id}; NI_KEYS: newer item id -> model name in the\n'
                '     Thunder 1.21.11 pack (see thunder-items.js). */\n')
        # newest step first: an item can be swapped more than once on its way down to 1.12
        order = ['VB|Protocol%sTo%s|id' % (cls(n), cls(p)) for n, p in reversed(STEPS)]
        tags = [[t, ids[t]] for t in order if t in ids]
        o.write('  var NI_TAGS=' + json.dumps(tags, sort_keys=True, separators=(',', ':')) + ';\n')
        o.write('  var NI_KEYS=' + json.dumps(keys, sort_keys=True, separators=(',', ':')) + ';\n')
    print('%d tags, %d item ids, %d model names -> %s' % (len(ids), total, len(keys), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    main()
